/* Generated by sdk/scripts/generate-artifact-manifest.mjs. Do not edit manually. */
export const OFFRAMP_ARTIFACT_MANIFEST = {
  "version": 1,
  "contractId": "offramp",
  "circuits": [
    "bindOffRampIntent",
    "proveAmountBinding",
    "proveComplianceFlag",
    "proveOffRampSettlement",
    "provePayeeBinding"
  ],
  "artifacts": [
    {
      "path": "contract/src/offramp.compact",
      "sha256": "5b1fed771ddd112870d7f73754694c400643171820298e85a9ee6676780905d8",
      "size": 6567
    },
    {
      "path": "contract/src/managed/offramp/compiler/contract-info.json",
      "runtimePath": "compiler/contract-info.json",
      "sha256": "8dd43bff89d31b07f1ebbf1b1f19e15a0e7d6164adafe5e32450b18c882f29a3",
      "size": 2979
    },
    {
      "path": "contract/src/managed/offramp/contract/index.js",
      "runtimePath": "contract/index.js",
      "sha256": "3f167e2f3a840013fb0245838fd23fa7a791eddb2d772161ca4fa852d8cea949",
      "size": 84540
    },
    {
      "path": "contract/src/managed/offramp/keys/bindOffRampIntent.prover",
      "runtimePath": "keys/bindOffRampIntent.prover",
      "sha256": "8b4521e84fcda69b975d5ee128bc2741d237e5441771017d6ab7dbaab223b048",
      "size": 147021
    },
    {
      "path": "contract/src/managed/offramp/keys/bindOffRampIntent.verifier",
      "runtimePath": "keys/bindOffRampIntent.verifier",
      "sha256": "0cbb5e6cc391d25a095ecffd131b4d7c38810733e3d1389badf01f615e80083f",
      "size": 1351
    },
    {
      "path": "contract/src/managed/offramp/keys/proveAmountBinding.prover",
      "runtimePath": "keys/proveAmountBinding.prover",
      "sha256": "e5d152810072aeaf8afe65f45980e643f546cb58b5039d7f17f232bb209c4943",
      "size": 2820327
    },
    {
      "path": "contract/src/managed/offramp/keys/proveAmountBinding.verifier",
      "runtimePath": "keys/proveAmountBinding.verifier",
      "sha256": "2c4b6c720c44f7dd189b334a36c06759af13bd25a7212c94c901557668955345",
      "size": 2119
    },
    {
      "path": "contract/src/managed/offramp/keys/proveComplianceFlag.prover",
      "runtimePath": "keys/proveComplianceFlag.prover",
      "sha256": "0d43791418edf0b5582f776ec42a932aebbbdb10c5179d30b853d24211a7e7c6",
      "size": 279605
    },
    {
      "path": "contract/src/managed/offramp/keys/proveComplianceFlag.verifier",
      "runtimePath": "keys/proveComplianceFlag.verifier",
      "sha256": "8dfcf9af81cd0fd0ef7c80a7102722359bef1e95dfd17cd59e880ed94ab13758",
      "size": 1351
    },
    {
      "path": "contract/src/managed/offramp/keys/proveOffRampSettlement.prover",
      "runtimePath": "keys/proveOffRampSettlement.prover",
      "sha256": "fd2c41c495f4f91ceb9fa1745cd9686c18353c007517daef4cec7022a27d765d",
      "size": 5201573
    },
    {
      "path": "contract/src/managed/offramp/keys/proveOffRampSettlement.verifier",
      "runtimePath": "keys/proveOffRampSettlement.verifier",
      "sha256": "6a7574c50d0a751aab95768f2237811183b83511ff1b35d67079bf472d6ca840",
      "size": 2119
    },
    {
      "path": "contract/src/managed/offramp/keys/provePayeeBinding.prover",
      "runtimePath": "keys/provePayeeBinding.prover",
      "sha256": "d7df3529da5712349bae48ca7ee52b69a898232a18c9ac95769fcf2adc7643ff",
      "size": 2820355
    },
    {
      "path": "contract/src/managed/offramp/keys/provePayeeBinding.verifier",
      "runtimePath": "keys/provePayeeBinding.verifier",
      "sha256": "08fdeeb3cdc7099bc9257fc86a99a5cdc6c60836c4ad2e20ee39f3befbe81b0c",
      "size": 2119
    },
    {
      "path": "contract/src/managed/offramp/zkir/bindOffRampIntent.bzkir",
      "runtimePath": "zkir/bindOffRampIntent.bzkir",
      "sha256": "b4483b374cb7807adf3669c8a474a32b903e2a40e34c22533a477e7834611860",
      "size": 155
    },
    {
      "path": "contract/src/managed/offramp/zkir/bindOffRampIntent.zkir",
      "runtimePath": "zkir/bindOffRampIntent.zkir",
      "sha256": "1d3dbf3e01634678151166eb14542b701a9648b91d264423fc48805b0692f3d9",
      "size": 2415
    },
    {
      "path": "contract/src/managed/offramp/zkir/proveAmountBinding.bzkir",
      "runtimePath": "zkir/proveAmountBinding.bzkir",
      "sha256": "8c556168678282f77e6bf51ed20586b4536afa919b815669bd3af6b59b43dd1b",
      "size": 256
    },
    {
      "path": "contract/src/managed/offramp/zkir/proveAmountBinding.zkir",
      "runtimePath": "zkir/proveAmountBinding.zkir",
      "sha256": "f6f5ffb4129953b37ca21a852698be81d5dfe2e4ae1c1b41b841dd828641daaa",
      "size": 4066
    },
    {
      "path": "contract/src/managed/offramp/zkir/proveComplianceFlag.bzkir",
      "runtimePath": "zkir/proveComplianceFlag.bzkir",
      "sha256": "bb0123f6ad2817d0fe281a60d9fd62f9709c7710c8b30ef4e9e4eb69de88a97e",
      "size": 281
    },
    {
      "path": "contract/src/managed/offramp/zkir/proveComplianceFlag.zkir",
      "runtimePath": "zkir/proveComplianceFlag.zkir",
      "sha256": "dbe8e5e0eb85d54083f6b74b384a6b31ea6acde183cd02395b233f2eabe5b561",
      "size": 4782
    },
    {
      "path": "contract/src/managed/offramp/zkir/proveOffRampSettlement.bzkir",
      "runtimePath": "zkir/proveOffRampSettlement.bzkir",
      "sha256": "3360cae9b1a7b0c8ee4c0206971ac21c35139e4491cbb477da9ceb1a2980dc5c",
      "size": 385
    },
    {
      "path": "contract/src/managed/offramp/zkir/proveOffRampSettlement.zkir",
      "runtimePath": "zkir/proveOffRampSettlement.zkir",
      "sha256": "69b2c502781a27cad90d5d94d3aad8701648ac7139d485d67720b745b63628f6",
      "size": 6110
    },
    {
      "path": "contract/src/managed/offramp/zkir/provePayeeBinding.bzkir",
      "runtimePath": "zkir/provePayeeBinding.bzkir",
      "sha256": "c879541c6708b0b2b91f941ba60966ca768d98cdccfa6a060efb13df8a3d64dd",
      "size": 271
    },
    {
      "path": "contract/src/managed/offramp/zkir/provePayeeBinding.zkir",
      "runtimePath": "zkir/provePayeeBinding.zkir",
      "sha256": "46bccecea4b668cb51dc1169fa732ffc041ac9439235976c55167477eb6d29ad",
      "size": 4313
    }
  ]
} as const;

export const OFFRAMP_ARTIFACT_MANIFEST_HASH = "37bf29a720a3451c0de6479a976161fbc8350dc64c0dc4bc9d2448386dc7e7cc";
